### ISSUE TITLE
Unhandled exception during Download ODPS. AttributeError: object has no attribute 'author'

### ISSUE THREAD

**Issue by ruscourier** [steinarb/opds-reader#26]
calibre, version 5.1.0
ERROR: Unhandled exception: <b>AttributeError</b>:object has no attribute 'author'

calibre 5.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: OPDS Client (1, 0, 0)
Traceback (most recent call last):
  File "site-packages/feedparser.py", line 398, in __getattr__
  File "site-packages/feedparser.py", line 356, in __getitem__
KeyError: 'author'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "calibre_plugins.opds_client.main", line 182, in download_opds
  File "calibre_plugins.opds_client.model", line 97, in downloadOpdsCatalog
  File "calibre_plugins.opds_client.model", line 143, in makeMetadataFromParsedOpds
  File "calibre_plugins.opds_client.model", line 148, in opdsToMetadata
  File "site-packages/feedparser.py", line 400, in __getattr__
AttributeError: object has no attribute 'author'

![opds](https://user-images.githubusercontent.com/61388836/94998354-f6a48d80-05b9-11eb-9bf0-c3fabe84ec68.png)

**Comment by steinarb** [comment]
@ruscourier can you update to the latest version and try? (remember to re-run "calibre-customize.exe -b ." after doing "git pull")

**Comment by ruscourier** [comment]
It work's! 10xs
