### ISSUE TITLE
ERROR: Unhandled exception: <b>ValueError</b>:unconverted data remains: +02:00

### ISSUE THREAD

**Issue by ruscourier** [steinarb/opds-reader#27]
Hi, please can you fix it? This happens to the OPDS catalog https://flibusta.site/opds

calibre, version 5.1.0
ERROR: Unhandled exception: <b>ValueError</b>:unconverted data remains: +02:00

calibre 5.1  embedded-python: True is64bit: True
macOS-10.15.7-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '19.6.0', 'Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64')
Python 3.8.5
OSX: ('10.15.7', ('', '', ''), 'x86_64')
Interface language: None
Successfully initialized third party plugins: OPDS Client (1, 0, 0)
Traceback (most recent call last):
  File "calibre_plugins.opds_client.main", line 182, in download_opds
  File "calibre_plugins.opds_client.model", line 97, in downloadOpdsCatalog
  File "calibre_plugins.opds_client.model", line 143, in makeMetadataFromParsedOpds
  File "calibre_plugins.opds_client.model", line 153, in opdsToMetadata
  File "lib/python3.8/_strptime.py", line 568, in _strptime_datetime
  File "lib/python3.8/_strptime.py", line 352, in _strptime
ValueError: unconverted data remains: +02:00

**Comment by ruscourier** [comment]
![flibusta](https://user-images.githubusercontent.com/61388836/94999537-a978e980-05c2-11eb-82c8-2947b5b1b973.png)

**Comment by steinarb** [comment]
@ruscourier an attempted fix has been pushed
