### ISSUE TITLE
Error while saving/applying configuration

### ISSUE THREAD

**Issue by grv87** [steinarb/opds-reader#38]
I changed configuration and pressed Ok. And got this:
```
calibre, version 6.13.0
ОШИБКА: Необработанное прерывание:: <b>ModuleNotFoundError</b>:No module named 'config'

calibre 6.13  embedded-python: True
Windows-10-10.0.19045-SP0 Windows ('64bit', 'WindowsPE')
('Windows', '10', '10.0.19045')
Python 3.10.1
Windows: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Interface language: ru
Successfully initialized third party plugins: AudioBook_Duration (1, 0, 9) && BookFusion Plugin (0, 8, 0) && Extract ISBN (1, 6, 0) && GetFileName (0, 2, 0) && Import List (1, 9, 0) && Job Spy (1, 0, 205) && KOReader Sync (0, 4, 1) && Libgen Fiction (0, 4, 0) && Library Codes (1, 0, 54) && Library Genesis (1, 2, 0) && OPDS Client (1, 0, 0) && Reading List (1, 15, 1) && TextDiff (1, 1, 2) && Wikidata (2, 0, 0) && Wikidata gui (2, 0, 0) && Zotero Metadata Importer (1, 0, 78)
Traceback (most recent call last):
  File "calibre\gui2\preferences\plugins.py", line 301, in customize_plugin
  File "calibre\gui2\preferences\plugins.py", line 379, in modify_plugin
  File "calibre\customize\__init__.py", line 177, in do_user_config
  File "calibre_plugins.opds_client.__init__", line 37, in save_settings
  File "calibre_plugins.opds_client.ui", line 28, in apply_settings
ModuleNotFoundError: No module named 'config'
```

I suppose this line:
https://github.com/steinarb/opds-reader/blob/4c21b06771ee9de11b5d088bc05cd3ffa804eb93/calibre_plugin/ui.py#L28
should be
```python
        from .config import prefs
```

Calibre 6.13.0.

**Comment by steinarb** [comment]
Hm... code untouched since August 2015... I can't remember.

I will have to look into it!

**Comment by steinarb** [comment]
I think I just took a plugin example and started hacking until it worked the way I wanted it to.

Should it perhaps be something like what is shown here? https://manual.calibre-ebook.com/creating_plugins.html#ui-py

I.e.
```
    def apply_settings(self):
        from calibre_plugins.interface_demo.config import prefs
        # In an actual non trivial plugin, you would probably need to
        # do something based on the settings in prefs
        prefs
```

Hm... but since I don't actually do anything with the prefs, do I need to implement something here...?

Could this perhaps be fixed by removing the apply_settings() method?
