### ISSUE TITLE
cannot import name feedparser

### ISSUE THREAD

**Issue by ramon-kramer** [steinarb/opds-reader#6]
Hi, i get an error on calibre 3:

Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 156, in __init__
    ac = self.init_iaction(action)
  File "/usr/lib/calibre/calibre/gui2/ui.py", line 170, in init_iaction
    ac = action.load_actual_plugin(self)
  File "/usr/lib/calibre/calibre/customize/__init__.py", line 614, in load_actual_plugin
    ac = getattr(importlib.import_module(mod), cls)(gui,
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 183, in load_module
    exec compiled in mod.__dict__
  File "calibre_plugins.opds_client.ui", line 9, in <module>
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 183, in load_module
    exec compiled in mod.__dict__
  File "calibre_plugins.opds_client.main", line 12, in <module>
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 183, in load_module
    exec compiled in mod.__dict__
  File "calibre_plugins.opds_client.model", line 12, in <module>
ImportError: cannot import name feedparser
I think calibre changed something. Installing python module (pip install feedparser) did not help.

regards

**Comment by steinarb** [comment]
FWIW it works for me on calibre 4.15.

But note that I install from the official installers on both windows and
GNU/linux, since the author doesn't accept bug reports against other
versions.
